// Registry validation script — run by CI on every push. Generated by the Artifisio sync; do not edit.
// Bundles @artifisio/schema's validateManifest / validateSetMeta so the registry repo needs no dependencies.
import { createHash } from 'node:crypto'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

"use strict";
var __schema = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // packages/schema/src/index.ts
  var index_exports = {};
  __export(index_exports, {
    DEFAULT_LICENSES: () => DEFAULT_LICENSES,
    REGISTRY_KINDS: () => REGISTRY_KINDS,
    SCHEMA_VERSION: () => SCHEMA_VERSION,
    injectSvgCssVars: () => injectSvgCssVars,
    items: () => items,
    kindOf: () => kindOf,
    resolveLicense: () => resolveLicense,
    validateManifest: () => validateManifest,
    validateSetMeta: () => validateSetMeta
  });
  var SCHEMA_VERSION = 2;
  var REGISTRY_KINDS = ["illustration", "icon", "font"];
  var ARTIFISIO = "Artifisio (https://artifisio.com)";
  var CC_BY_URL = "https://creativecommons.org/licenses/by/4.0/";
  var DEFAULT_LICENSES = {
    illustration: { spdx: "CC-BY-4.0", attributionRequired: true, attribution: `Illustrations by ${ARTIFISIO}`, url: CC_BY_URL },
    icon: { spdx: "CC-BY-4.0", attributionRequired: true, attribution: `Icons by ${ARTIFISIO}`, url: CC_BY_URL },
    font: { spdx: "OFL-1.1", attributionRequired: true, attribution: `Fonts by ${ARTIFISIO}`, url: "https://openfontlicense.org" },
    logo: { spdx: "LicenseRef-Artifisio-Premium", attributionRequired: false }
  };
  function kindOf(set) {
    return set.kind ?? "illustration";
  }
  function items(set) {
    if (set.kind === "font") return [];
    return set.kind === "icon" ? set.icons : set.illustrations;
  }
  function resolveLicense(set, kind = kindOf(set)) {
    const defaults = DEFAULT_LICENSES[kind];
    const own = set.license;
    if (!own) return { ...defaults };
    const license = { spdx: own.spdx, attributionRequired: own.attributionRequired };
    if (own.attributionRequired) license.attribution = own.attribution ?? defaults.attribution;
    const url = own.url ?? (own.spdx === defaults.spdx ? defaults.url : void 0);
    if (url) license.url = url;
    return license;
  }
  var isObj = (v) => typeof v === "object" && v !== null && !Array.isArray(v);
  var isNonEmptyString = (v) => typeof v === "string" && v.length > 0;
  var isStringArray = (v) => Array.isArray(v) && v.every((s) => typeof s === "string");
  function validateFile(file, path, errors) {
    if (!isObj(file) || !isNonEmptyString(file.file)) errors.push(`${path}: missing file path`);
  }
  function validatePalette(palette, path, errors) {
    if (!Array.isArray(palette)) {
      errors.push(`${path}: palette must be an array`);
      return;
    }
    for (const slot of palette) {
      if (!isObj(slot) || !isNonEmptyString(slot.slot)) errors.push(`${path} > slot: missing slot`);
      if (!isObj(slot) || !isNonEmptyString(slot.label)) errors.push(`${path} > slot: missing label`);
      if (!isObj(slot) || !isNonEmptyString(slot.hex)) errors.push(`${path} > slot: missing hex`);
      if (!isObj(slot) || slot.role !== "themeable" && slot.role !== "fixed") {
        errors.push(`${path} > slot: role must be "themeable" or "fixed"`);
      }
    }
  }
  function validateItems(items2, path, label, errors) {
    if (!Array.isArray(items2)) {
      errors.push(`${path}: ${label} must be an array`);
      return;
    }
    for (const item of items2) {
      if (!isObj(item) || !isNonEmptyString(item.slug)) {
        errors.push(`${path} > ${label.slice(0, -1)}: missing slug`);
        continue;
      }
      const itemPath = `${path} > ${item.slug}`;
      if (!isNonEmptyString(item.defaultVariant)) errors.push(`${itemPath}: missing defaultVariant`);
      if (!isObj(item.variants)) {
        errors.push(`${itemPath}: missing variants`);
        continue;
      }
      if (isNonEmptyString(item.defaultVariant) && !item.variants[item.defaultVariant]) {
        errors.push(`${itemPath}: defaultVariant "${item.defaultVariant}" not in variants`);
      }
      for (const [fmt, variant] of Object.entries(item.variants)) validateFile(variant, `${itemPath} > ${fmt}`, errors);
    }
  }
  function validateCount(meta, items2, path, label, errors) {
    if (typeof meta.count === "number" && Array.isArray(items2) && items2.length !== meta.count) {
      errors.push(`${path}: count ${meta.count} does not match ${items2.length} ${label}`);
    }
  }
  function validateIllustrationSet(meta, path, errors) {
    validateItems(meta.illustrations, path, "illustrations", errors);
    validateCount(meta, meta.illustrations, path, "illustrations", errors);
  }
  function validateIconSet(meta, path, errors) {
    if (typeof meta.grid !== "number") errors.push(`${path}: grid must be a number`);
    validateItems(meta.icons, path, "icons", errors);
    validateCount(meta, meta.icons, path, "icons", errors);
    if (meta.sprite !== void 0) validateFile(meta.sprite, `${path} > sprite`, errors);
  }
  function validateFontSet(meta, path, errors) {
    if (!isNonEmptyString(meta.family)) errors.push(`${path}: missing family`);
    if (!isStringArray(meta.scripts)) errors.push(`${path}: scripts must be an array of strings`);
    if (!Array.isArray(meta.styles)) {
      errors.push(`${path}: styles must be an array`);
      return;
    }
    for (const style of meta.styles) {
      if (!isObj(style) || !isNonEmptyString(style.name)) {
        errors.push(`${path} > style: missing name`);
        continue;
      }
      const stylePath = `${path} > ${style.name}`;
      if (typeof style.weight !== "number") errors.push(`${stylePath}: weight must be a number`);
      if (!isObj(style.files) || Object.keys(style.files).length === 0) {
        errors.push(`${stylePath}: missing files`);
        continue;
      }
      for (const [fmt, file] of Object.entries(style.files)) validateFile(file, `${stylePath} > ${fmt}`, errors);
    }
  }
  var KIND_VALIDATORS = {
    illustration: validateIllustrationSet,
    icon: validateIconSet,
    font: validateFontSet
  };
  function validateSetMeta(meta, path = "set") {
    const errors = [];
    if (!isObj(meta)) return [`${path}: must be an object`];
    if (!isNonEmptyString(meta.slug)) errors.push(`${path}: missing slug`);
    if (!isNonEmptyString(meta.name)) errors.push(`${path}: missing name`);
    if (!isNonEmptyString(meta.description)) errors.push(`${path}: missing description`);
    if (typeof meta.count !== "number") errors.push(`${path}: count must be a number`);
    if (meta.tags !== void 0 && !isStringArray(meta.tags)) errors.push(`${path}: tags must be an array of strings`);
    if (meta.license !== void 0) {
      const license = meta.license;
      if (!isObj(license) || !isNonEmptyString(license.spdx)) errors.push(`${path} > license: missing spdx`);
      if (!isObj(license) || typeof license.attributionRequired !== "boolean") {
        errors.push(`${path} > license: attributionRequired must be a boolean`);
      }
    }
    if (meta.provenance !== void 0) {
      const source = isObj(meta.provenance) ? meta.provenance.source : void 0;
      if (source !== "hand-made" && source !== "generated") errors.push(`${path} > provenance: source must be "hand-made" or "generated"`);
    }
    const kind = meta.kind === void 0 ? "illustration" : meta.kind;
    const validateKind = KIND_VALIDATORS[kind];
    if (!validateKind) {
      errors.push(`${path}: unsupported kind "${String(kind)}" (expected ${REGISTRY_KINDS.join(" | ")})`);
      return errors;
    }
    validateKind(meta, path, errors);
    if (kind !== "font" && meta.palette !== void 0) validatePalette(meta.palette, `${path} > palette`, errors);
    return errors;
  }
  function validateManifest(manifest) {
    const errors = [];
    if (!isObj(manifest)) return ["manifest: must be an object"];
    const { schemaVersion, registryVersion, kind, sets } = manifest;
    if (schemaVersion !== void 0) {
      if (!Number.isInteger(schemaVersion) || schemaVersion < 1) errors.push("manifest: schemaVersion must be a positive integer");
      else if (schemaVersion > SCHEMA_VERSION) errors.push(`manifest: schemaVersion ${schemaVersion} is newer than supported ${SCHEMA_VERSION}`);
    }
    if (registryVersion !== void 0 && typeof registryVersion !== "string") errors.push("manifest: registryVersion must be a string");
    if (kind !== void 0 && !REGISTRY_KINDS.includes(kind)) {
      errors.push(`manifest: unsupported kind "${String(kind)}" (expected ${REGISTRY_KINDS.join(" | ")})`);
    }
    if (!isObj(sets)) return [...errors, "manifest: missing sets object"];
    const manifestKind = kindOf(manifest);
    for (const [key, set] of Object.entries(sets)) {
      const path = `manifest.sets > ${key}`;
      errors.push(...validateSetMeta(set, path));
      if (!isObj(set)) continue;
      if (set.slug !== void 0 && set.slug !== key) errors.push(`${path}: slug "${String(set.slug)}" does not match key`);
      const setKind = kindOf(set);
      if (setKind !== manifestKind) errors.push(`${path}: kind "${setKind}" does not match manifest kind "${manifestKind}"`);
    }
    return errors;
  }
  function injectSvgCssVars(svgText, palette, userColors) {
    const overrides = palette.filter((s) => s.role === "themeable" && userColors[s.slot]).map((s) => `--artf-${s.slot}: ${userColors[s.slot]}`);
    if (!overrides.length) return svgText;
    const styleValue = overrides.join("; ");
    if (/style\s*=\s*["']/.test(svgText.slice(0, 500))) {
      return svgText.replace(/(<svg[^>]*style\s*=\s*["'])/, `$1${styleValue}; `);
    }
    return svgText.replace(/(<svg\b)/, `$1 style="${styleValue}"`);
  }
  return __toCommonJS(index_exports);
})();

const { validateManifest, validateSetMeta, kindOf } = __schema

let errors = 0
const fail = (msg) => { console.error('  FAIL:', msg); errors++ }
const sha256 = (buf) => createHash('sha256').update(buf).digest('hex')

function filesOf(set) {
  const kind = kindOf(set)
  if (kind === 'font') return set.styles.flatMap((s) => Object.values(s.files))
  const items = kind === 'icon' ? set.icons : set.illustrations
  return items.flatMap((i) => Object.values(i.variants)).concat(set.sprite ? [set.sprite] : [])
}

console.log('Validating manifest.json...')
const manifest = JSON.parse(readFileSync('manifest.json', 'utf-8'))
for (const e of validateManifest(manifest)) fail(e)

console.log('Validating sets/*/meta.json and file checksums...')
for (const slug of existsSync('sets') ? readdirSync('sets') : []) {
  const metaPath = join('sets', slug, 'meta.json')
  if (!existsSync(metaPath)) { fail(metaPath + ': missing'); continue }
  const meta = JSON.parse(readFileSync(metaPath, 'utf-8'))
  for (const e of validateSetMeta(meta, metaPath)) fail(e)
  if (!manifest.sets?.[slug]) { fail(metaPath + ': not listed in manifest.json'); continue }
  if (JSON.stringify(meta) !== JSON.stringify(manifest.sets[slug])) fail(metaPath + ': differs from manifest.json')
  for (const file of filesOf(meta)) {
    const p = join('sets', slug, file.file)
    if (!existsSync(p)) { fail(p + ': missing file'); continue }
    const buf = readFileSync(p)
    if (file.sha256 && sha256(buf) !== file.sha256) fail(p + ': sha256 mismatch')
    if (file.bytes !== undefined && buf.length !== file.bytes) fail(p + ': byte size mismatch')
  }
}
for (const slug of Object.keys(manifest.sets ?? {})) {
  if (!existsSync(join('sets', slug, 'meta.json'))) fail('manifest.json > ' + slug + ': sets/' + slug + '/meta.json missing')
}

if (errors > 0) {
  console.error('\n' + errors + ' validation error(s) found.')
  process.exit(1)
}
console.log('\nValidated ' + Object.keys(manifest.sets ?? {}).length + ' sets — OK.')
